**1. Broadcasting**


In [6]:
import numpy as np

marks = np.array([
    [88, 96, 95],
    [72, 99, 91],
    [98, 85, 97],
    [60, 75, 80]
])

bonus = np.array([5, 2, 8])
updated_marks = marks + bonus
capped_marks = np.minimum(updated_marks, 100)
capped_count = np.sum(updated_marks > 100)

print("Updated marks:")
print(capped_marks)

print("Number of marks capped:", capped_count)

Updated marks:
[[ 93  98 100]
 [ 77 100  99]
 [100  87 100]
 [ 65  77  88]]
Number of marks capped: 4


**2.5×5 Border Matrix**

In [7]:
matrix = np.zeros((5, 5), dtype=int)

matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**3.Reshape and Transpose**

In [8]:
arr = np.arange(30).reshape(5, -1).T

print(arr)
print("Shape:", arr.shape)

# np.arange(30).reshape(4, -1) fails because
# 30 elements cannot be evenly divided into 4 rows.

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]
Shape: (6, 5)


**4.hstack vs Two-Column Table**

In [9]:
import numpy as np

heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

combined = np.hstack((heights, weights))

print("hstack result:")
print(combined)
print("Shape:", combined.shape)

table = np.column_stack((heights, weights))

print("\nTwo-column table:")
print(table)
print("Shape:", table.shape)

hstack result:
[172 158 181 166  68  52  84  59]
Shape: (8,)

Two-column table:
[[172  68]
 [158  52]
 [181  84]
 [166  59]]
Shape: (4, 2)


**5.Quarterly Sales**

In [10]:
sales = np.array([
    120, 135, 98,
    160, 175, 190,
    88, 92, 105,
    210, 198, 230
])

quarters = sales.reshape(4, 3)

quarter_averages = quarters.mean(axis=1)

highest_quarter = np.argmax(quarter_averages)
highest_average = quarter_averages[highest_quarter]

print("Quarterly sales:")
print(quarters)

print("Quarter averages:", quarter_averages)
print("Highest quarter index:", highest_quarter)
print("Highest average:", highest_average)

Quarterly sales:
[[120 135  98]
 [160 175 190]
 [ 88  92 105]
 [210 198 230]]
Quarter averages: [117.66666667 175.          95.         212.66666667]
Highest quarter index: 3
Highest average: 212.66666666666666


**6.Multiplication Table Using Broadcasting**


In [11]:
a = np.array([2, 3, 4])

# Reshape one operand into a column
multiplication_table = a.reshape(-1, 1) * a

print(multiplication_table)
print("Shape:", multiplication_table.shape)

[[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]
Shape: (3, 3)


**7.Replace Multiples of 3**

In [12]:
import numpy as np
arr = np.arange(1, 21)

arr[arr % 3 == 0] = -1

print(arr)

[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]


**8.Column-wise Min-Max Normalization**

In [13]:
import numpy as np

X = np.array([
    [50, 1200, 3],
    [80, 1500, 9],
    [65, 900, 5],
    [95, 2000, 7]
])

column_min = X.min(axis=0)
column_max = X.max(axis=0)

normalized = (X - column_min) / (column_max - column_min)

print("Normalized matrix:")
print(normalized)

print("\nColumn minimums:")
print(normalized.min(axis=0))

print("\nColumn maximums:")
print(normalized.max(axis=0))

Normalized matrix:
[[0.         0.27272727 0.        ]
 [0.66666667 0.54545455 1.        ]
 [0.33333333 0.         0.33333333]
 [1.         1.         0.66666667]]

Column minimums:
[0. 0. 0.]

Column maximums:
[1. 1. 1.]


**9.Medal Assignment**

In [14]:
import numpy as np
scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])

medals = np.where(
    scores >= 90,
    "Gold",
    np.where(
        scores >= 75,
        "Silver",
        np.where(
            scores >= 60,
            "Bronze",
            "None"
        )
    )
)

print("Medals:")
print(medals)

gold_count = np.sum(medals == "Gold")
silver_count = np.sum(medals == "Silver")
bronze_count = np.sum(medals == "Bronze")
none_count = np.sum(medals == "None")

print("Gold:", gold_count)
print("Silver:", silver_count)
print("Bronze:", bronze_count)
print("None:", none_count)

Medals:
['Gold' 'Bronze' 'Silver' 'None' 'Gold' 'Silver' 'None' 'Bronze']
Gold: 2
Silver: 2
Bronze: 2
None: 2


**10.Elements Greater Than 50**

In [15]:
import numpy as np
m = np.array([
    [10, 80, 45],
    [55, 20, 99],
    [70, 33, 12]
])

rows, columns = np.where(m > 50)

print("Row indices:", rows)
print("Column indices:", columns)


print("Elements greater than 50:", m[m > 50])


new_m = m.copy()


new_m[np.where(new_m > 50)] = 0

print("Modified copy:")
print(new_m)

print("Original matrix:")
print(m)

Row indices: [0 1 1 2]
Column indices: [1 0 2 0]
Elements greater than 50: [80 55 99 70]
Modified copy:
[[10  0 45]
 [ 0 20  0]
 [ 0 33 12]]
Original matrix:
[[10 80 45]
 [55 20 99]
 [70 33 12]]


**11.Sensor Stacking**

In [16]:
import numpy as np
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])


sensor_rows = np.vstack((s1, s2, s3))


sensor_columns = np.column_stack((s1, s2, s3))

print("Sensors as rows:")
print(sensor_rows)
print("Shape:", sensor_rows.shape)

print("\nSensors as columns:")
print(sensor_columns)
print("Shape:", sensor_columns.shape)

print("\nIs one transpose of the other?")
print(np.array_equal(sensor_rows.T, sensor_columns))

Sensors as rows:
[[12 15 11 19 14]
 [22 18 25 21 20]
 [31 35 29 33 30]]
Shape: (3, 5)

Sensors as columns:
[[12 22 31]
 [15 18 35]
 [11 25 29]
 [19 21 33]
 [14 20 30]]
Shape: (5, 3)

Is one transpose of the other?
True


**13.Matrix Multiplication**

In [17]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8, 9],
    [1, 0, 2]
])

result1 = A @ B.T
result2 = A.T @ B

print("A @ B.T:")
print(result1)
print("Shape:", result1.shape)

print("\nA.T @ B:")
print(result2)
print("Shape:", result2.shape)

A @ B.T:
[[ 50   7]
 [122  16]]
Shape: (2, 2)

A.T @ B:
[[11  8 17]
 [19 16 28]
 [27 24 39]]
Shape: (3, 3)


**14.Complete NumPy Pipeline**

In [18]:
import numpy as np
hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])

hours_col = hours.reshape(-1, 1)
attendance_col = attendance.reshape(-1, 1)

print("hours_col shape:", hours_col.shape)
print("attendance_col shape:", attendance_col.shape)

table = np.hstack((hours_col, attendance_col))

print("\nTwo-column table:")
print(table)
print("Shape:", table.shape)

totals = hours + attendance
totals_col = totals.reshape(-1, 1)

print("\nTotals:")
print(totals_col)
print("Shape:", totals_col.shape)

three_column_table = np.hstack((table, totals_col))

print("\nThree-column table:")
print(three_column_table)
print("Shape:", three_column_table.shape)

w = np.array([0.5, 0.2, 0.3])

scores = three_column_table @ w

print("\nScores:")
print(scores)
print("Shape:", scores.shape)

average_score = scores.mean()

result = np.where(scores > average_score, 1, 0)

print("\nAverage score:", average_score)
print("Final result:", result)
print("Shape:", result.shape)

hours_col shape: (6, 1)
attendance_col shape: (6, 1)

Two-column table:
[[ 2 55]
 [ 8 92]
 [ 5 70]
 [10 98]
 [ 3 60]
 [ 7 85]]
Shape: (6, 2)

Totals:
[[ 57]
 [100]
 [ 75]
 [108]
 [ 63]
 [ 92]]
Shape: (6, 1)

Three-column table:
[[  2  55  57]
 [  8  92 100]
 [  5  70  75]
 [ 10  98 108]
 [  3  60  63]
 [  7  85  92]]
Shape: (6, 3)

Scores:
[29.1 52.4 39.  57.  32.4 48.1]
Shape: (6,)

Average score: 43.0
Final result: [0 1 0 1 0 1]
Shape: (6,)


**15.Min-Max Normalization**

In [19]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

normalized = (arr - arr.min()) / (arr.max() - arr.min())

print("Original:")
print(arr)

print("\nNormalized:")
print(normalized)

Original:
[10 20 30 40 50]

Normalized:
[0.   0.25 0.5  0.75 1.  ]


**16.flatten() and ravel()**

In [20]:
import numpy as np
m = np.array([
    [4, 8, 15],
    [16, 23, 42]
])

flat_array = m.flatten()
ravel_array = m.ravel()

flat_array[0] = 999
ravel_array[0] = 999

print("Flatten array:")
print(flat_array)

print("\nRavel array:")
print(ravel_array)

print("\nOriginal matrix:")
print(m)

Flatten array:
[999   8  15  16  23  42]

Ravel array:
[999   8  15  16  23  42]

Original matrix:
[[999   8  15]
 [ 16  23  42]]


**17.Temperature Analysis**

In [21]:
import numpy as np
np.random.seed(7)

temps = np.random.randint(15, 41, 28)

weeks = temps.reshape(4, 7)

weekly_average = weeks.mean(axis=1)

hottest_week = np.argmax(weekly_average)

days_above_35 = np.sum(temps > 35)

print("Temperature data:")
print(temps)

print("\n4 weeks:")
print(weeks)

print("\nWeekly averages:")
print(weekly_average)

print("\nHottest week index:", hottest_week)
print("Hottest week average:", weekly_average[hottest_week])

print("\nNumber of days above 35:", days_above_35)

Temperature data:
[30 19 40 37 18 34 38 22 40 29 38 23 40 29 25 23 22 21 19 31 22 27 15 26
 38 21 34 27]

4 weeks:
[[30 19 40 37 18 34 38]
 [22 40 29 38 23 40 29]
 [25 23 22 21 19 31 22]
 [27 15 26 38 21 34 27]]

Weekly averages:
[30.85714286 31.57142857 23.28571429 26.85714286]

Hottest week index: 1
Hottest week average: 31.571428571428573

Number of days above 35: 7


**18.Matrix Multiplication Order**

In [22]:
import numpy as np
np.random.seed(10)

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

AB = A @ B
BA = B @ A

print("A:")
print(A)

print("\nB:")
print(B)

print("\nA @ B:")
print(AB)

print("\nB @ A:")
print(BA)

print("\nAre A @ B and B @ A equal?")
print(np.array_equal(AB, BA))


A:
[[5 1 2]
 [1 2 9]
 [1 9 7]]

B:
[[5 4 1]
 [5 7 9]
 [2 9 5]]

A @ B:
[[ 34  45  24]
 [ 33  99  64]
 [ 64 130 117]]

B @ A:
[[ 30  22  53]
 [ 41 100 136]
 [ 24  65 120]]

Are A @ B and B @ A equal?
False


**19.Marks and Topper**

In [23]:
import numpy as np
marks = np.array([
    [45, 28, 67, 80],
    [33, 90, 55, 41],
    [72, 66, 30, 58],
    [88, 79, 91, 84],
    [25, 40, 38, 52]
])

updated_marks = np.maximum(marks, 35)

totals = updated_marks.sum(axis=1)

topper_index = np.argmax(totals)
topper_total = totals[topper_index]

print("Updated marks:")
print(updated_marks)

print("\nStudent totals:")
print(totals)

print("\nTopper index:", topper_index)
print("Topper total:", topper_total)

Updated marks:
[[45 35 67 80]
 [35 90 55 41]
 [72 66 35 58]
 [88 79 91 84]
 [35 40 38 52]]

Student totals:
[227 221 231 342 165]

Topper index: 3
Topper total: 342


**20.Slice and Copy**

In [24]:
import numpy as np
arr = np.arange(1, 11)

slice_array = arr[2:6]
copy_array = arr[2:6].copy()

slice_array[0] = 999
copy_array[0] = 999

print("Original array:")
print(arr)

print("\nSlice:")
print(slice_array)

print("\nCopy:")
print(copy_array)


Original array:
[  1   2 999   4   5   6   7   8   9  10]

Slice:
[999   4   5   6]

Copy:
[999   4   5   6]


**21.np.diag()**

In [25]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Extract diagonal
diagonal = np.diag(matrix)

print("Diagonal:")
print(diagonal)

# Create diagonal matrix from 1D array
arr = np.array([10, 20, 30, 40])

diagonal_matrix = np.diag(arr)

print("\nDiagonal matrix:")
print(diagonal_matrix)

Diagonal:
[ 1  6 11 16]

Diagonal matrix:
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
